# Generated by Django 3.1.5 on 2021-01-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('profilepic', models.ImageField(upload_to='profiles/')),
                ('bio', models.TextField()),
                ('Phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Landing', models.ImageField(upload_to='landings/')),
                ('Description', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awardsapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design', models.IntegerField()),
                ('Usability', models.IntegerField()),
                ('Content', models.IntegerField()),
                ('Average', models.IntegerField()),
                ('Rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awardsapp.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awardsapp.project')),
            ],
        ),
    ]
