# Generated by Django 3.1.5 on 2021-01-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AwardsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Landing', models.ImageField(upload_to='landings/')),
                ('Description', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AwardsApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design', models.IntegerField()),
                ('Usability', models.IntegerField()),
                ('Content', models.IntegerField()),
                ('Average', models.IntegerField()),
                ('RatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AwardsApp.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AwardsApp.project')),
            ],
        ),
    ]
