# Generated by Django 3.1.5 on 2021-01-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwardsApp', '0002_project_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='RatedBy',
            new_name='Rater',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='Phone',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
