# Generated by Django 3.1.5 on 2021-01-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0002_auto_20210127_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Landing',
            field=models.ImageField(upload_to='landigs/'),
        ),
    ]
